### ISSUE TITLE
addwstr() error

### ISSUE THREAD

**Issue by joker234** [pajowu/fahrgastrechte-autofill#2]
If I want to test your program using this commands:
```
pip3 install -r requirements.txt
python3 fahrgastrechte.py
```

I got the following error:
```
Traceback (most recent call last):
  File "fahrgastrechte.py", line 177, in <module>
    print(main())
  File "fahrgastrechte.py", line 50, in main
    return npyscreen.wrapper_basic(functools.partial(run_menu, defaults, args))
  File "/home/user/.local/lib/python3.6/site-packages/npyscreen/npyssafewrapper.py", line 19, in wrapper_basic
    return curses.wrapper(call_function)
  File "/usr/lib/python3.6/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "fahrgastrechte.py", line 73, in run_menu
    npyscreen.TitleMultiLine, values=fields[n]['FieldStateOption'], name=title, value=i)))
  File "/home/user/.local/lib/python3.6/site-packages/npyscreen/fmFormMultiPage.py", line 74, in add_widget_intelligent
    return self.add_widget(*args, **keywords)
  File "/home/user/.local/lib/python3.6/site-packages/npyscreen/fmForm.py", line 384, in add_widget
    *args, **keywords)
  File "/home/user/.local/lib/python3.6/site-packages/npyscreen/wgtitlefield.py", line 69, in __init__
    self.make_contained_widgets()
  File "/home/user/.local/lib/python3.6/site-packages/npyscreen/wgtitlefield.py", line 86, in make_contained_widgets
    self.label_widget = textbox.Textfield(self.parent, relx=self.relx, rely=self.rely, width=len(self.name)+1, value=self.name, color=self.labelColor)
  File "/home/user/.local/lib/python3.6/site-packages/npyscreen/wgtextbox.py", line 44, in __init__
    self.update()
  File "/home/user/.local/lib/python3.6/site-packages/npyscreen/wgtextbox.py", line 132, in update
    self._print()
  File "/home/user/.local/lib/python3.6/site-packages/npyscreen/wgtextbox.py", line 299, in _print
    color
_curses.error: addwstr() returned ERR
```

Commands like `python3 fahrgastrechte.py -h` work as intended. The `pip3` command worked like I expected.

**Comment by pajowu** [comment]
Sorry for the late reply. This is not an error in my code but in the library I am using. Can you try using a bigger terminal window, this only happens to me when I use a smaller window

**Comment by joker234** [comment]
First it worked like you mentioned with a larger window. But now I get this error with every terminal window size. Is it possible to modify or replace the `npyscreen.TitleMultiLine` with `npyscreen.MultiLine` in [fahrgastrechte.py#L73](https://github.com/pajowu/fahrgastrechte-autofill/blob/04f597becc1bfd8f808d3b59f882e717ab812a69/fahrgastrechte.py#L73)?

**Comment by pajowu** [comment]
That should not fix the error. The TitleMultiLine is used if the form fields has a title set. If we use `MultiLine` instead, the title would not be shown so we would just have a huge number of text input fields without a title

**Comment by joker234** [comment]
with the current code:
```
$ python3 fahrgastrechte.py                      
Traceback (most recent call last):                   
  File "fahrgastrechte.py", line 177, in <module>
    print(main())
  File "fahrgastrechte.py", line 50, in main
    return npyscreen.wrapper_basic(functools.partial(run_menu, defaults, args))
  File "/home/user/folder/fahrgastrechte-autofill/venv/lib/python3.6/site-packages/npyscreen/npyssafewrapper.py", line 19, in wrapper_basic
    return curses.wrapper(call_function)
  File "/usr/lib/python3.6/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "fahrgastrechte.py", line 73, in run_menu
    npyscreen.TitleMultiLine, values=fields[n]['FieldStateOption'], name=title, value=i)))
  File "/home/user/folder/fahrgastrechte-autofill/venv/lib/python3.6/site-packages/npyscreen/fmFormMultiPage.py", line 74, in add_widget_intelligent
    return self.add_widget(*args, **keywords)
  File "/home/user/folder/fahrgastrechte-autofill/venv/lib/python3.6/site-packages/npyscreen/fmForm.py", line 384, in add_widget
    *args, **keywords)
  File "/home/user/folder/fahrgastrechte-autofill/venv/lib/python3.6/site-packages/npyscreen/wgtitlefield.py", line 69, in __init__
    self.make_contained_widgets()
  File "/home/user/folder/fahrgastrechte-autofill/venv/lib/python3.6/site-packages/npyscreen/wgtitlefield.py", line 86, in make_contained_widgets
    self.label_widget = textbox.Textfield(self.parent, relx=self.relx, rely=self.rely, width=len(self.name)+1, value=self.name, color=self.labelColor)
  File "/home/user/folder/fahrgastrechte-autofill/venv/lib/python3.6/site-packages/npyscreen/wgtextbox.py", line 44, in __init__
    self.update()
  File "/home/user/folder/fahrgastrechte-autofill/venv/lib/python3.6/site-packages/npyscreen/wgtextbox.py", line 132, in update
    self._print()
  File "/home/user/folder/fahrgastrechte-autofill/venv/lib/python3.6/site-packages/npyscreen/wgtextbox.py", line 299, in _print
    color
_curses.error: addwstr() returned ERR
```

with the modification:
![screenshot_2018-03-08_15-53-13_ 0100](https://user-images.githubusercontent.com/2878899/37157332-d9c8728c-22e8-11e8-8423-8b0cc11e7cf4.jpg)
```diff
diff --git a/fahrgastrechte.py b/fahrgastrechte.py
index 5b3fbe5..2a34b5e 100644
--- a/fahrgastrechte.py
+++ b/fahrgastrechte.py
@@ -70,7 +70,7 @@ def run_menu(defaults, args, *arg, **kwargs):
                 i = fields[n]['FieldStateOption'].index('Off')
             if title:
                 field_fields.append((n, F.add_widget_intelligent(
-                    npyscreen.TitleMultiLine, values=fields[n]['FieldStateOption'], name=title, value=i)))
+                    npyscreen.MultiLine, values=fields[n]['FieldStateOption'], name=title, value=i)))
             else:
                 field_fields.append((n, F.add_widget_intelligent(
                     npyscreen.MultiLine, values=fields[n]['FieldStateOption'], value=i)))
```

Which title is missing here?

**Comment by pajowu** [comment]
Please try the new tkinter based interface `fahrgastrechte_tkinter.py`

**Comment by stkdiretto** [comment]
Reopening this, because `fahrgastrechte_tkinter.py` exits without even drawing a window for me, and I can't rely on increasing the terminal window size when using my setups (which usually include VT100s or teletype interfaces)

**Comment by pajowu** [comment]
Please try again with the `staging` branch. It contains both a workaround for the addwstr error and a bugfix for the not opening tkinter window

**Comment by TheRojam** [comment]
staging works. 🎉
