### ISSUE TITLE
Is the project is still alive?

### ISSUE THREAD

**Issue by steinbrueckri** [pajowu/fahrgastrechte-autofill#8]
Hi folks 👋

I just wanted to ask if the project is still alive. ;)

```
Traceback (most recent call last):
  File "fahrgastrechte.py", line 75, in <module>
    print(main())
  File "fahrgastrechte.py", line 20, in main
    args, defaults = functions.get_args()
  File "/Users/steinbrueckri/Projects/steinbrueckri/fahrgastrechte-autofill/functions.py", line 59, in get_args
    livedata = get_livedata(**vars(args))
  File "/Users/steinbrueckri/Projects/steinbrueckri/fahrgastrechte-autofill/functions.py", line 203, in get_livedata
    return trip_info.json()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)
``` 

It doesn't work for me at the moment because of the following error message. The only question is, is it possible to fix this or is the "API" no longer available?

cheers 🍻  Richard

**Comment by steinbrueckri** [comment]
Hi, guys,
I just close the ticket, I found a nice alternative with [robin-zug ](http://robin-zug.de/en) ;)

Cheers Richard

**Comment by pajowu** [comment]
The "Livedata" API changes often. It is propably available but I can only update once I'm in an ICE train again.

**Comment by steinbrueckri** [comment]
@pajowu What do you need exactly there? I have a BahnCard 100 and travel frequently between Erfurt and Gotha. If you tell me what you need, I can do some curl request the next time.

**Comment by pajowu** [comment]
I just checked while travelling and the API was still available and worked with the current code. If you want you can check the next time you are in an ICE train:
- Open the ICE Portal
- Check in the "Developer Tools" in the "Network"-Tab if there is a request to "trip" and if yes please post the URL and the response here (today it was `https://iceportal.de/api1/rs/tripInfo/trip`)
